# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

stages:
  - test
  - deploy

before_script:
  - npm install gulp-cli -g
  - npm install

test:6:
  stage: test
  image: node:6
  script:
    - gulp
  except:
    - master

test:7:
  stage: test
  image: node:7
  script:
    - gulp
  except:
    - master

test:8:
  stage: test
  image: node:8
  script:
    - gulp
  except:
    - master

test:9:
  stage: test
  image: node:9
  script:
    - gulp
  except:
    - master

test:10:
  stage: test
  image: node:10
  script:
    - gulp
  except:
    - master

pages:
  stage: deploy
  image: node:8
  script:
    - gulp
    - mkdir public
    - mv build/* public/
  artifacts:
    paths:
      - public
  only:
    - master
